<?php
/**
 * settings.php - Organization Settings
 */

require_once __DIR__ . '/auth.php';
use Core\Database\DBConnection;

$user = requireEnterpriseAuth();
$pdo = getDBConnection();
$orgId = getOrganizationId();
$userRole = $user['role'] ?? 'viewer';
$fullName = $user['full_name'] ?? $user['username'] ?? 'User';
$orgName = $user['organization_name'] ?? 'Organization'; // RAW — shell-head.php escapes itself, pre-escaping causes double-escaping

$canManageUsers = in_array($userRole, ['owner', 'it_manager_enterprise', 'it_officer_enterprise'], true);

function safeHtml($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}
function getRoleLabel($role) {
    $labels = [
        'owner' => 'Owner', 'it_manager_enterprise' => 'IT Manager', 'it_officer_enterprise' => 'IT Officer',
        'it_support' => 'IT Support', 'department_head' => 'Department Head', 'program_officer' => 'Uploader',
        'finance_officer' => 'Finance Officer', 'approver' => 'Approver', 'senior_approver' => 'Senior Approver',
        'supervisor' => 'Supervisor', 'beneficiary_registrar' => 'Beneficiary Registrar', 'auditor' => 'Auditor', 'viewer' => 'Viewer',
    ];
    return $labels[$role] ?? ucfirst(str_replace('_', ' ', $role));
}

// ============================================================
// SHARED SHELL SETUP — same contract as every other redesigned page,
// so this page's nav is generated by the exact same code, not a
// hand-copied lookalike.
// ============================================================
$isTopRole = in_array($userRole, ['owner', 'it_manager_enterprise'], true);
$isDepartmentHead = ($userRole === 'department_head');
$canCreate = in_array($userRole, ['owner', 'it_manager_enterprise', 'program_officer', 'department_head'], true);
$canApprove = in_array($userRole, ['owner', 'approver', 'senior_approver', 'it_manager_enterprise'], true);
$canSeeSourceAccountsArea = in_array($userRole, ['owner', 'it_manager_enterprise', 'finance_officer'], true);
$canTrace = in_array($userRole, ['owner', 'it_manager_enterprise', 'it_officer_enterprise', 'auditor', 'senior_approver', 'approver', 'finance_officer'], true);
$canManageDepartments = $isTopRole;
$setupReady = true; // every remaining page requires an authenticated, already-onboarded user to reach at all

// Same live badge numbers the dashboard and other pages show, so a
// count on "Disbursements" or "Source Accounts" never disagrees
// depending on which page you're on.
$navPendingApprovals = 0;
$navPendingSourceConfirmations = 0;
try {
    if ($canApprove) {
        $stmt = $pdo->prepare("SELECT COUNT(*) FROM disbursement_batches WHERE organization_id = :org_id AND status IN ('pending','pending_approval','PENDING','PENDING_APPROVAL')");
        $stmt->execute([':org_id' => $orgId]);
        $navPendingApprovals = (int)$stmt->fetchColumn();
    }
    if ($canSeeSourceAccountsArea) {
        $stmt = $pdo->prepare("SELECT COUNT(*) FROM source_accounts WHERE organization_id = :org_id AND status = 'pending_confirmation' AND deleted_at IS NULL");
        $stmt->execute([':org_id' => $orgId]);
        $navPendingSourceConfirmations = (int)$stmt->fetchColumn();
    }
} catch (PDOException $e) {
    error_log("[settings] Nav badge query error: " . $e->getMessage());
}

$basePath = '';
$navItems = [
    ['key' => 'dashboard', 'icon' => 'grid', 'label' => 'Dashboard', 'href' => 'index.php', 'show' => true],
    ['key' => 'disbursements', 'icon' => 'wallet', 'label' => 'Disbursements', 'href' => 'batches/index.php?status=all', 'show' => true, 'badge' => ($navPendingApprovals > 0 && $canApprove) ? $navPendingApprovals : null],
    ['key' => 'beneficiaries', 'icon' => 'people', 'label' => 'Beneficiaries', 'href' => 'beneficiaries.php', 'show' => true],
    ['key' => 'trace', 'icon' => 'search', 'label' => 'Trace Payment', 'href' => 'index.php#trace', 'show' => $canTrace],
    ['key' => 'departments', 'icon' => 'building', 'label' => 'Departments', 'href' => 'departments/index.php', 'show' => $canManageDepartments || $isDepartmentHead],
    ['key' => 'sources', 'icon' => 'bank', 'label' => 'Source Accounts', 'href' => 'imports/add_source.php', 'show' => $canSeeSourceAccountsArea, 'badge' => $navPendingSourceConfirmations > 0 ? $navPendingSourceConfirmations : null],
    ['key' => 'team', 'icon' => 'idcard', 'label' => 'Team', 'href' => 'settings/users.php', 'show' => $canManageUsers],
    ['key' => 'reports', 'icon' => 'chart', 'label' => 'Reports', 'href' => 'reports.php', 'show' => true],
];
$navUtility = [
    ['key' => 'settings', 'icon' => 'gear', 'label' => 'Settings', 'href' => 'settings.php', 'show' => true, 'active' => true],
    ['key' => 'logout', 'icon' => 'logout', 'label' => 'Log Out', 'href' => 'logout.php', 'show' => true],
];
$topbarSearchShow = $canTrace;
$topbarSearchAction = 'index.php';
$topbarSearchName = 'trace';
$topbarSearchPlaceholder = 'Search batch reference, phone, national ID…';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VOUCHMORPH · Settings · <?php echo safeHtml($orgName); ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Sans+Condensed:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="partials/shell.css">
</head>
<body>
    <?php require __DIR__ . '/partials/shell-head.php'; ?>
            <div class="page-header">
                <div>
                    <h1>Settings</h1>
                    <div class="sub">Manage organization users, source accounts, and configuration.</div>
                </div>
            </div>

            <div class="panel">
                <div class="panel-head">
                    <span class="title"><?php echo svgIcon('gear'); ?> Settings Categories</span>
                </div>
                <div class="panel-body">
                    <?php if ($canManageUsers): ?>
                    <div class="task-row">
                        <span class="dot green"></span>
                        <div class="body">
                            <span class="label">👤 User Management</span>
                            <div class="meta">Manage organization users, roles, and permissions.</div>
                            <div class="cta"><a href="settings/users.php" class="btn-mini outline">Manage Users</a></div>
                        </div>
                    </div>
                    <?php endif; ?>

                    <div class="task-row">
                        <span class="dot green"></span>
                        <div class="body">
                            <span class="label">🏦 Source Accounts</span>
                            <div class="meta">Manage your organization's source accounts for disbursements.</div>
                            <div class="cta"><a href="imports/add_source.php" class="btn-mini outline">Manage Sources</a></div>
                        </div>
                    </div>

                    <div class="task-row locked">
                        <span class="dot muted"></span>
                        <div class="body">
                            <span class="label">📋 Organization Profile</span>
                            <div class="meta">View and update organization details and preferences.</div>
                            <div class="cta"><button type="button" class="btn-mini locked-btn" disabled><?php echo svgIcon('lock'); ?> Coming Soon</button></div>
                        </div>
                    </div>

                    <div class="task-row locked">
                        <span class="dot muted"></span>
                        <div class="body">
                            <span class="label">🔐 Security Settings</span>
                            <div class="meta">Configure security preferences and audit logs.</div>
                            <div class="cta"><button type="button" class="btn-mini locked-btn" disabled><?php echo svgIcon('lock'); ?> Coming Soon</button></div>
                        </div>
                    </div>
                </div>
            </div>
        <?php
        $dbHealthy = DBConnection::isConnected();
        $footerStatusLine = 'LEDGER SYNC: ' . ($dbHealthy ? '<span class="ok">OK</span>' : '<span class="bad">DEGRADED</span>');
        require __DIR__ . '/partials/shell-foot.php';
        ?>
</body>
</html>
