<?php
declare(strict_types=1);
/**
 * Agent/Organization-initiated account registration.
 *
 * Lets an approved agent or an organization staff member open a
 * VouchMorph account on behalf of someone else, using any identity
 * type (phone, email, national_id, drivers_license, passport) plus a
 * phone-or-email contact channel for verification.
 *
 * Unlike self-service registration, the PIN is NEVER chosen by the
 * agent - it is randomly generated by the system and sent directly
 * to the account owner's contact channel, so the agent never learns
 * or can guess the owner's PIN.
 *
 * Two-step flow, mirroring register.php/verify_otp.php:
 *   action=initiate -> validates + sends OTP to the owner's contact
 *   action=  -> verifies OTP, creates the account, generates
 *                       + sends the PIN
 */

ob_start();
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

define('PROJECT_ROOT', dirname(__DIR__, 4));

require_once PROJECT_ROOT . '/src/Core/Config/LoadCountry.php';
require_once PROJECT_ROOT . '/src/Application/Utils/SessionManager.php';
require_once PROJECT_ROOT . '/src/Core/Database/DBConnection.php';
require_once PROJECT_ROOT . '/src/Core/Database/AuthDBConnection.php';
require_once PROJECT_ROOT . '/src/Core/Database/CredentialsRepository.php';
require_once PROJECT_ROOT . '/src/Core/Factories/CommunicationFactory.php';
require_once PROJECT_ROOT . '/src/Infrastructure/Email/Contracts/EmailProviderInterface.php';
require_once PROJECT_ROOT . '/src/Infrastructure/Email/EmailGatewayClient.php';
require_once PROJECT_ROOT . '/src/Domain/Models/Permission.php';

use Application\Utils\SessionManager;
use Core\Database\DBConnection;
use Core\Database\CredentialsRepository;
use Core\Factories\CommunicationFactory;
use Infrastructure\Email\EmailGatewayClient;

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed. Use POST.']);
    exit();
}

SessionManager::start();
if (!SessionManager::isLoggedIn()) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'You must be logged in to register an account on behalf of someone else.']);
    exit();
}
$actingUser = SessionManager::getUser();
$actingUserId = (int)($actingUser['user_id'] ?? 0);

try {
    $config = \Core\Config\LoadCountry::getConfig();
} catch (Throwable $e) {
    error_log("REGISTER_IDENTITY_OWNER: Config error: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'System configuration error.']);
    exit();
}

$systemCountry   = $config['country'] ?? getenv('VM_COUNTRY') ?? 'BW';
$countryConfig   = $config['country_settings'][$systemCountry] ?? [];
$countryName     = $countryConfig['name'] ?? $systemCountry;
$countryDialCode = $countryConfig['dial_code'] ?? '+267';

try {
    $db = DBConnection::getConnection();
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Throwable $e) {
    error_log("REGISTER_IDENTITY_OWNER DB ERROR: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'Database connection failed.']);
    exit();
}

// ============================================================
// PERMISSION CHECK: acting user must be an approved agent, or hold
// an explicit role permission to register identities for others.
// ============================================================
function callerCanRegisterOthers(PDO $db, int $userId): bool
{
    // Approved agent (mirrors SwapService::isApprovedAgent logic)
    $stmt = $db->prepare("
        SELECT 1 FROM agent_destination_accounts
        WHERE user_id = :user_id AND status = 'active' AND deleted_at IS NULL
        LIMIT 1
    ");
    $stmt->execute([':user_id' => $userId]);
    if ($stmt->fetchColumn()) {
        return true;
    }

    // Explicit role-based permission (organization staff, ops, etc.)
    $stmt = $db->prepare("SELECT role_id FROM users WHERE user_id = :id");
    $stmt->execute([':id' => $userId]);
    $roleId = $stmt->fetchColumn();
    if (!$roleId) {
        return false;
    }

    $permission = new \Permission($db);
    $permissions = $permission->getByRole((int)$roleId);
    foreach ($permissions as $p) {
        if (($p['name'] ?? '') === 'register_identity_owner') {
            return true;
        }
    }
    return false;
}

if (!callerCanRegisterOthers($db, $actingUserId)) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'You are not authorized to register accounts on behalf of others. Become an approved agent, or ask VouchMorph to grant your organization this permission.']);
    exit();
}

// ============================================================
// Helpers (mirrors register.php)
// ============================================================
function normalizePhone(string $phoneInput, string $dialCode): string
{
    $phoneInput = preg_replace('/[^\d+]/', '', trim($phoneInput));
    if ($phoneInput === '') return '';
    if (str_starts_with($phoneInput, '+')) {
        return '+' . preg_replace('/[^0-9]/', '', substr($phoneInput, 1));
    }
    return $dialCode . ltrim($phoneInput, '0');
}

function generateOTP(): string
{
    return str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);
}

function generateRandomPin(): string
{
    // System-generated PIN for agent/org-created accounts - the agent
    // never chooses or sees this; it is delivered only to the owner.
    return str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);
}

function maskDestination(string $value, string $type): string
{
    if ($type === 'email' && str_contains($value, '@')) {
        [$local, $domain] = explode('@', $value, 2);
        $visible = substr($local, 0, 1);
        return $visible . str_repeat('•', max(1, strlen($local) - 1)) . '@' . $domain;
    }
    $len = strlen($value);
    if ($len <= 4) return str_repeat('•', $len);
    return substr($value, 0, 3) . str_repeat('•', max(0, $len - 6)) . substr($value, -3);
}

function sendEmail(EmailGatewayClient $emailClient, string $to, string $subject, string $message): bool
{
    $result = $emailClient->sendEmail($to, $subject, $message);
    return $result['success'] ?? false;
}

function userExistsByIdentity(PDO $db, string $identityType, string $identityValue, ?string $contactPhone, ?string $contactEmail): ?array
{
    $columnMap = [
        'phone' => 'phone',
        'email' => 'email',
        'national_id' => 'national_id',
        'drivers_license' => 'drivers_license',
        'passport' => 'passport',
    ];

    $conditions = [];
    $params = [];

    if (isset($columnMap[$identityType])) {
        $conditions[] = "{$columnMap[$identityType]} = :primary";
        $params[':primary'] = $identityValue;
    }
    if (!empty($contactPhone)) {
        $conditions[] = "(phone = :cphone OR phone2 = :cphone OR phone3 = :cphone)";
        $params[':cphone'] = $contactPhone;
    }
    if (!empty($contactEmail)) {
        $conditions[] = "email = :cemail";
        $params[':cemail'] = $contactEmail;
    }

    if (empty($conditions)) {
        return null;
    }

    $stmt = $db->prepare("SELECT user_id, full_name, phone, email FROM users WHERE " . implode(' OR ', $conditions) . " LIMIT 1");
    $stmt->execute($params);
    return $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
}

// ============================================================
// Main request handling
// ============================================================
$input = json_decode(file_get_contents('php://input'), true) ?? $_POST;
$action = $input['action'] ?? 'initiate';

try {

    if ($action === 'initiate') {
        $identityType  = trim($input['identity_type'] ?? '');
        $identityValue = trim($input['identity_value'] ?? '');
        $fullName      = trim($input['full_name'] ?? '');
        $dateOfBirth   = trim($input['date_of_birth'] ?? '');
        $contactChannel = $input['contact_channel'] ?? null; // 'phone' or 'email'
        $contactValue   = trim($input['contact_value'] ?? '');
        $organizationName = trim($input['organization_name'] ?? ''); // optional, for audit only

        $validIdentityTypes = ['phone', 'email', 'national_id', 'drivers_license', 'passport'];
        if (!in_array($identityType, $validIdentityTypes, true)) {
            echo json_encode(['success' => false, 'message' => 'Invalid identity_type. Must be one of: ' . implode(', ', $validIdentityTypes)]);
            exit();
        }
        if ($identityValue === '') {
            echo json_encode(['success' => false, 'message' => 'identity_value is required']);
            exit();
        }

        // Determine the identity value + the OTP contact channel
        $phoneNumber = null;
        $emailAddress = null;
        $normalizedIdentityValue = $identityValue;

        if ($identityType === 'phone') {
            $normalizedIdentityValue = normalizePhone($identityValue, $countryDialCode);
            $phoneNumber = $normalizedIdentityValue;
            $otpChannel = 'sms';
            $otpDestination = $phoneNumber;
        } elseif ($identityType === 'email') {
            if (!filter_var($identityValue, FILTER_VALIDATE_EMAIL)) {
                echo json_encode(['success' => false, 'message' => 'Invalid email address format.']);
                exit();
            }
            $normalizedIdentityValue = strtolower($identityValue);
            $emailAddress = $normalizedIdentityValue;
            $otpChannel = 'email';
            $otpDestination = $emailAddress;
        } else {
            // national_id / drivers_license / passport - a phone or
            // email contact is mandatory, exactly like self-registration.
            if (empty($contactChannel) || empty($contactValue)) {
                echo json_encode(['success' => false, 'message' => 'A phone number or email is required for this person so we can send their verification code and PIN.']);
                exit();
            }
            if ($contactChannel === 'phone') {
                $otpChannel = 'sms';
                $otpDestination = normalizePhone($contactValue, $countryDialCode);
                $phoneNumber = $otpDestination;
            } elseif ($contactChannel === 'email') {
                if (!filter_var($contactValue, FILTER_VALIDATE_EMAIL)) {
                    echo json_encode(['success' => false, 'message' => 'Please enter a valid email address.']);
                    exit();
                }
                $otpChannel = 'email';
                $otpDestination = strtolower(trim($contactValue));
                $emailAddress = $otpDestination;
            } else {
                echo json_encode(['success' => false, 'message' => 'contact_channel must be "phone" or "email".']);
                exit();
            }
        }

        // Duplicate check - identity value AND contact channel
        $existing = userExistsByIdentity($db, $identityType, $normalizedIdentityValue, $phoneNumber, $emailAddress);
        if ($existing) {
            echo json_encode([
                'success' => false,
                'message' => 'An account already exists for this identity or contact.',
                'exists' => true,
            ]);
            exit();
        }

        // Generate + store OTP (proves the contact channel is real and
        // that the owner consents to the account being opened)
        $otpPlain = generateOTP();
        $otpHash = password_hash($otpPlain, PASSWORD_DEFAULT);
        $expiresAt = date('Y-m-d H:i:s', time() + 300);
        $ipAddress = $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'] ?? 'unknown';
        $userAgent = $_SERVER['HTTP_USER_AGENT'] ?? 'unknown';

        $stmt = $db->prepare("UPDATE otp_logs SET used_at = NOW() WHERE identifier = :identifier AND used_at IS NULL");
        $stmt->execute([':identifier' => $otpDestination]);

        $dbIdentifierType = ($otpChannel === 'sms') ? 'phone' : 'email';
        $stmt = $db->prepare("
            INSERT INTO otp_logs
            (identifier, identifier_type, code_hash, purpose, expires_at, attempts, ip_address, user_agent, created_at)
            VALUES
            (:identifier, :identifier_type, :code_hash, 'registration', :expires_at, 0, :ip_address, :user_agent, NOW())
        ");
        $stmt->execute([
            ':identifier' => $otpDestination,
            ':identifier_type' => $dbIdentifierType,
            ':code_hash' => $otpHash,
            ':expires_at' => $expiresAt,
            ':ip_address' => $ipAddress,
            ':user_agent' => $userAgent,
        ]);

        $_SESSION['agent_registration'][$otpDestination] = [
            'identity_type' => $identityType,
            'identity_value' => $normalizedIdentityValue,
            'full_name' => $fullName,
            'date_of_birth' => $dateOfBirth,
            'phone_number' => $phoneNumber,
            'email' => $emailAddress,
            'otp_channel' => $otpChannel,
            'otp_destination' => $otpDestination,
            'registered_by_agent_id' => $actingUserId,
            'organization_name' => $organizationName,
        ];

        $otpSent = false;
        if ($otpChannel === 'sms') {
            try {
                $comm = CommunicationFactory::createForPhone('sms', $otpDestination);
                $result = $comm->send($otpDestination, "VouchMorph: An account is being opened for you. Verification code: {$otpPlain}. If you did not expect this, ignore this message.");
                $otpSent = (bool)($result['success'] ?? false);
            } catch (Throwable $e) {
                error_log("REGISTER_IDENTITY_OWNER: SMS failed: " . $e->getMessage());
            }
        } else {
            try {
                $emailClient = new EmailGatewayClient($config['email'] ?? []);
                $otpSent = sendEmail(
                    $emailClient,
                    $otpDestination,
                    "Verify your new VouchMorph account",
                    "<p>An account is being opened for you on VouchMorph {$countryName}.</p><p>Your verification code is: <strong style='font-size:22px;'>{$otpPlain}</strong></p><p>This code expires in 5 minutes. Never share it with anyone.</p><p>If you did not expect this, you can ignore this email.</p>"
                );
            } catch (Throwable $e) {
                error_log("REGISTER_IDENTITY_OWNER: Email failed: " . $e->getMessage());
            }
        }

        if (!$otpSent) {
            echo json_encode(['success' => false, 'message' => 'Unable to send the verification code right now. Please try again shortly.']);
            exit();
        }

        echo json_encode([
            'success' => true,
            'message' => 'Verification code sent to ' . maskDestination($otpDestination, $otpChannel === 'sms' ? 'phone' : 'email'),
            'otp_destination_masked' => maskDestination($otpDestination, $otpChannel === 'sms' ? 'phone' : 'email'),
        ]);
        exit();
    }

    if ($action === '') {
        $otpDestinationInput = trim($input['otp_destination'] ?? '');
        $otp = trim($input['otp'] ?? '');

        if (empty($otp) || !preg_match('/^\d{6}$/', $otp)) {
            echo json_encode(['success' => false, 'message' => 'Please enter a valid 6-digit verification code.']);
            exit();
        }

        if (!isset($_SESSION['agent_registration'][$otpDestinationInput])) {
            echo json_encode(['success' => false, 'message' => 'Registration session expired. Please start again.']);
            exit();
        }
        $tempData = $_SESSION['agent_registration'][$otpDestinationInput];

        $stmt = $db->prepare("
            SELECT otp_id, code_hash, expires_at, attempts
            FROM otp_logs
            WHERE identifier = :identifier
              AND purpose = 'registration'
              AND used_at IS NULL
            ORDER BY created_at DESC
            LIMIT 1
        ");
        $stmt->execute([':identifier' => $tempData['otp_destination']]);
        $otpRecord = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$otpRecord) {
            echo json_encode(['success' => false, 'message' => 'Verification code not found. Please request a new code.']);
            exit();
        }
        if (strtotime($otpRecord['expires_at']) < time()) {
            echo json_encode(['success' => false, 'message' => 'Verification code has expired. Please start again.']);
            exit();
        }
        if ($otpRecord['attempts'] >= 5) {
            echo json_encode(['success' => false, 'message' => 'Too many failed attempts. Please start again.']);
            exit();
        }
        if (!password_verify($otp, $otpRecord['code_hash'])) {
            $stmt = $db->prepare("UPDATE otp_logs SET attempts = attempts + 1 WHERE otp_id = :otp_id");
            $stmt->execute([':otp_id' => $otpRecord['otp_id']]);
            echo json_encode(['success' => false, 'message' => 'Invalid verification code. Please try again.']);
            exit();
        }

        $stmt = $db->prepare("UPDATE otp_logs SET used_at = NOW() WHERE otp_id = :otp_id");
        $stmt->execute([':otp_id' => $otpRecord['otp_id']]);

        $db->beginTransaction();
        try {
            // Re-check for a race-condition duplicate right before insert
            $existing = userExistsByIdentity(
                $db,
                $tempData['identity_type'],
                $tempData['identity_value'],
                $tempData['phone_number'],
                $tempData['email']
            );
            if ($existing) {
                $db->rollBack();
                echo json_encode(['success' => false, 'message' => 'An account already exists for this identity or contact.']);
                exit();
            }

            $username = 'user_' . bin2hex(random_bytes(4));
            while (CredentialsRepository::userUsernameExists($username)) {
                $username = 'user_' . bin2hex(random_bytes(4));
            }

            $email = $tempData['email'];
            if (empty($email)) {
                $email = $username . '@' . strtolower($countryName) . '.vouchmorphn.com';
            }

            // System-generated PIN - the agent never sees or chooses this.
            $pin = generateRandomPin();
            $pinHash = password_hash($pin, PASSWORD_DEFAULT);

            $dateOfBirth = null;
            if (!empty($tempData['date_of_birth'])) {
                $ts = strtotime($tempData['date_of_birth']);
                if ($ts !== false) {
                    $dateOfBirth = date('Y-m-d', $ts);
                }
            }

            // ============================================================
            // FIX: Add must_change_pin flag to force PIN change on first login
            // The account owner will be prompted to change their PIN
            // immediately after their first successful login.
            // ============================================================
            // username/password_hash live in the isolated auth DB now (see
            // CredentialsRepository), written after this INSERT returns
            // the new user_id — the two databases can't share one
            // transaction.
            $stmt = $db->prepare("
                INSERT INTO users (
                    email, phone,
                    transaction_pin_hash, transaction_pin_set_at,
                    verified, created_at,
                    national_id, drivers_license, passport,
                    date_of_birth, full_name,
                    registered_by_agent_id, registration_channel,
                    must_change_pin
                ) VALUES (
                    :email, :phone,
                    :transaction_pin_hash, NOW(),
                    true, NOW(),
                    :national_id, :drivers_license, :passport,
                    :date_of_birth, :full_name,
                    :registered_by_agent_id, :registration_channel,
                    true
                )
                RETURNING user_id
            ");
            $stmt->execute([
                ':email' => $email,
                ':phone' => $tempData['phone_number'],
                ':transaction_pin_hash' => $pinHash,
                ':national_id' => $tempData['identity_type'] === 'national_id' ? $tempData['identity_value'] : null,
                ':drivers_license' => $tempData['identity_type'] === 'drivers_license' ? $tempData['identity_value'] : null,
                ':passport' => $tempData['identity_type'] === 'passport' ? $tempData['identity_value'] : null,
                ':date_of_birth' => $dateOfBirth,
                ':full_name' => $tempData['full_name'] ?: null,
                ':registered_by_agent_id' => $tempData['registered_by_agent_id'],
                ':registration_channel' => !empty($tempData['organization_name']) ? 'organization' : 'agent',
            ]);

            $userId = (int)$stmt->fetchColumn();

            $db->commit();

            // The agent-generated PIN doubles as this account's login
            // password (see AuthService note elsewhere) — same value,
            // stored once in the auth DB.
            CredentialsRepository::createUserCredentials($userId, $username, $pinHash);

            // Send the PIN to the same verified contact channel
            $pinMessage = "Your VouchMorph account has been created. Your PIN is: {$pin}. For security, you will be required to change this PIN after your first login. Keep it private - never share it, even with the agent who helped you register.";
            if ($tempData['otp_channel'] === 'sms') {
                try {
                    $comm = CommunicationFactory::createForPhone('sms', $tempData['otp_destination']);
                    $comm->send($tempData['otp_destination'], $pinMessage);
                } catch (Throwable $e) {
                    error_log("REGISTER_IDENTITY_OWNER: Failed to SMS PIN to new user {$userId}: " . $e->getMessage());
                }
            } else {
                try {
                    $emailClient = new EmailGatewayClient($config['email'] ?? []);
                    sendEmail($emailClient, $tempData['otp_destination'], "Your VouchMorph PIN", "<p>{$pinMessage}</p>");
                } catch (Throwable $e) {
                    error_log("REGISTER_IDENTITY_OWNER: Failed to email PIN to new user {$userId}: " . $e->getMessage());
                }
            }

            unset($_SESSION['agent_registration'][$otpDestinationInput]);

            echo json_encode([
                'success' => true,
                'message' => 'Account created. The PIN has been sent to the owner\'s ' . ($tempData['otp_channel'] === 'sms' ? 'phone' : 'email') . '. They must change their PIN after first login.',
                'user_id' => $userId,
                'must_change_pin' => true,
            ]);

        } catch (Throwable $e) {
            $db->rollBack();
            error_log("REGISTER_IDENTITY_OWNER: user creation failed: " . $e->getMessage());
            echo json_encode(['success' => false, 'message' => 'Failed to create account: ' . $e->getMessage()]);
        }
        exit();
    }

    echo json_encode(['success' => false, 'message' => 'Invalid action. Must be "initiate" or "".']);

} catch (Throwable $e) {
    error_log("REGISTER_IDENTITY_OWNER ERROR: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'System error occurred.']);
}
